.PHONY: help setup install dev up down logs migrate seed test lint format clean

include .env
export

help: ## Show help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

setup: ## Initial project setup
	@echo "Installing dependencies..."
	pnpm install
	python -m pip install -e services/_common
	@test -f .env || cp .env.example .env
	@echo "Setup complete. Run 'make dev' to start."

bootstrap: ## Bootstraps Python environment and validates service registry
	python -m pip install -r pyproject.toml || python -m pip install -e services/_common
	python -c "from faccp_common.registry import load_registry; load_registry()"
	@echo "Bootstrap complete."

platform-check: ## Validate platform registry and service port availability
	python scripts/platform_check.py

platform-registry: ## Generate/export registry metadata
	python scripts/generate_registry.py

platform-health: ## Check platform health
	python scripts/platform_check.py

identity: ## Start identity service baseline
	python -m uvicorn services.identity.app.main:app --host 0.0.0.0 --port 8001

drunkit-mvp: ## Start drunkit-mvp backend API (:8000)
	cd services/drunkit-mvp && python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

drunkit-web: ## Start drunkit-web consumer frontend (:5173)
	pnpm --filter drunkit-consumer-web dev

drunkit-staff: ## Start drunkit-staff console (:5174)
	pnpm --filter drunkit-staff-console dev

drunkit-dev: ## Start full DrunkIt stack (MVP + Web + Staff)
	docker compose --profile core up

dev-infra: ## Start infrastructure only
	docker compose up -d postgres redis kafka minio mailhog otel-collector prometheus grafana jaeger loki
	@sleep 10
	@make kafka-create-topics

dev-services: ## Start all backend services
	@for service in identity-service consumer-service retailer-service catalog-service inventory-service order-service compliance-service audit-service risk-service verification-service delivery-service notification-service payment-service pricing-service analytics-service realtime-service drunkit-mvp; do \
		(cd services/$$service && python -m uvicorn app.main:app --host 0.0.0.0 --port $$(echo $$service | grep -oE '[0-9]+$$' || echo 8000) --reload) & \
	done
	@echo "Services starting..."

db-migrate: ## Run platform database migrations
	python -m alembic upgrade head

db-revision: ## Create autogenerated database migration revision
	python -m alembic revision --autogenerate -m "platform database migration"

db-check: ## Check platform database migration status
	python -m alembic check

migrate: ## Run all database migrations
	python -m alembic upgrade head || true
	@for service in identity-service consumer-service retailer-service catalog-service inventory-service order-service compliance-service audit-service risk-service verification-service delivery-service notification-service payment-service pricing-service analytics-service realtime-service drunkit-mvp; do \
		echo "Migrating $$service..."; \
		(cd services/$$service && alembic upgrade head) || echo "  (no migrations or failed)"; \
	done

seed: ## Seed initial data
	@echo "Seeding roles and permissions..."
	cd services/identity-service && python -m app.scripts.seed_rbac
	@echo "Seeding policies..."
	cd services/compliance-service && python -m app.scripts.seed_policies
	@echo "Seeding catalog..."
	cd services/catalog-service && python -m app.scripts.seed_catalog
	@echo "Seeding drunkit-mvp..."
	cd services/drunkit-mvp && python -m scripts.seed
	@echo "Seed complete."

test: ## Run unit and e2e tests
	python -m pytest tests/unit tests/e2e

lint: ## Run linters
	uv run ruff check .
	cd apps && pnpm lint

format: ## Format code
	uv run ruff format .
	cd apps && pnpm format
