"""Domain events generated by Compliance domain decision engine."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import ClassVar
from faccp_platform.events.contracts import DomainEvent


class EligibilityEvaluatedEvent(DomainEvent):
    event_type: ClassVar[str] = "compliance.eligibility.evaluated"
    decision_id: str
    consumer_id: str
    product_id: str
    jurisdiction_id: str
    status: str
    policy_id: str | None = None
    engine_version: str = "0.1.0"
