"""
Progressive Trust Levels (§14.3).
"""

from __future__ import annotations

from enum import Enum


class ConsumerTrustLevel(str, Enum):
    C0_GUEST = "C0_GUEST"
    C1_REGISTERED = "C1_REGISTERED"
    C2_IDENTITY_VERIFIED = "C2_IDENTITY_VERIFIED"
    C3_AGE_ELIGIBLE = "C3_AGE_ELIGIBLE"
    C4_TRANSACTION_VERIFIED = "C4_TRANSACTION_VERIFIED"


class RetailerTrustLevel(str, Enum):
    S0_APPLICATION = "S0_APPLICATION"
    S1_BUSINESS_VERIFIED = "S1_BUSINESS_VERIFIED"
    S2_LICENSE_VERIFIED = "S2_LICENSE_VERIFIED"
    S3_STORE_VERIFIED = "S3_STORE_VERIFIED"
    S4_OPERATIONALLY_VERIFIED = "S4_OPERATIONALLY_VERIFIED"
    S5_FULLY_COMPLIANT = "S5_FULLY_COMPLIANT"


class DriverTrustLevel(str, Enum):
    D0_APPLIED = "D0_APPLIED"
    D1_DOCUMENTS_SUBMITTED = "D1_DOCUMENTS_SUBMITTED"
    D2_BACKGROUND_CHECK_PASSED = "D2_BACKGROUND_CHECK_PASSED"
    D3_TRAINING_COMPLETED = "D3_TRAINING_COMPLETED"
    D4_ACTIVE = "D4_ACTIVE"
    D5_TRUSTED = "D5_TRUSTED"
