from enum import Enum


class DeliveryStatus(str, Enum):
    REQUESTED = "REQUESTED"
    PLANNING = "PLANNING"
    DISPATCHING = "DISPATCHING"
    ASSIGNED = "ASSIGNED"
    PICKUP_READY = "PICKUP_READY"
    PICKED_UP = "PICKED_UP"
    IN_TRANSIT = "IN_TRANSIT"
    ARRIVING = "ARRIVING"
    HANDOFF_PENDING = "HANDOFF_PENDING"
    DELIVERED = "DELIVERED"

    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    RETURN_REQUIRED = "RETURN_REQUIRED"
    RETURNED = "RETURNED"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    ADMIN = "ADMIN"
    RETAILER = "RETAILER"
    DRIVER = "DRIVER"
    CONSUMER = "CONSUMER"
