"""Domain events generated by Consumer domain actions."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import ClassVar
from pydantic import BaseModel, Field
from faccp_platform.events.contracts import DomainEvent


class ConsumerCreatedEvent(DomainEvent):
    event_type: ClassVar[str] = "consumer.created"
    consumer_id: str
    identity_id: str


class ConsumerActivatedEvent(DomainEvent):
    event_type: ClassVar[str] = "consumer.activated"
    consumer_id: str


class ConsumerVerificationCompletedEvent(DomainEvent):
    event_type: ClassVar[str] = "consumer.verification.completed"
    consumer_id: str
    verification_status: str
    verification_method: str
