class PaymentStatus:
    CREATED = "CREATED"
    PENDING = "PENDING"
    AUTHORIZED = "AUTHORIZED"
    CAPTURED = "CAPTURED"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    REFUNDED = "REFUNDED"
    FAILED = "FAILED"


PAYMENT_TRANSITIONS = {
    "PENDING": {"AUTHORIZED", "FAILED"},
    "AUTHORIZED": {"CAPTURED", "FAILED"},
    "CAPTURED": {"PARTIALLY_REFUNDED", "REFUNDED"},
    "PARTIALLY_REFUNDED": {"PARTIALLY_REFUNDED", "REFUNDED"},
    "REFUNDED": set(),
    "FAILED": set(),
}


class ReconciliationStatus:
    MATCHED = "MATCHED"
    MISSING_INTERNAL = "MISSING_INTERNAL"
    MISSING_PROVIDER = "MISSING_PROVIDER"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    STATUS_MISMATCH = "STATUS_MISMATCH"
    DUPLICATE = "DUPLICATE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    RESOLVED = "RESOLVED"
