apiVersion: v1
kind: Secret
metadata:
  name: drunkit-secrets
  namespace: drunkit
type: Opaque
stringData:
  DATABASE_PASSWORD: "CHANGE_ME"
  JWT_PRIVATE_KEY: "CHANGE_ME"
  JWT_PUBLIC_KEY: "CHANGE_ME"
