class ServiceabilityReason:

    OUTSIDE_SERVICE_AREA = "OUTSIDE_SERVICE_AREA"

    STORE_CLOSED = "STORE_CLOSED"

    NO_STORE_AVAILABLE = "NO_STORE_AVAILABLE"

    NO_INVENTORY = "NO_INVENTORY"

    RESTRICTED_AREA = "RESTRICTED_AREA"

    TEMPORARILY_UNAVAILABLE = "TEMPORARILY_UNAVAILABLE"
